version: "3"
services:
  homeassistant:
    container_name: home-assistant
    privileged: true
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Sofia
    ports:
      - 8123:8123
    restart: always
    network_mode: host
