version: "2.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    restart: always
    networks:
      - elastic

  log01:
    image: docker.elastic.co/logstash/logstash:7.9.0
    container_name: log01
    ports:
      - "5514:5514/tcp"
      - "5514:5514/udp"
      - 5600:5600
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/mikrotik:/usr/share/logstash/custom-patterns/mikrotik
      - ./logstash/mikrotik-log.conf:/usr/share/logstash/pipeline/01-mikrotik.conf
    restart: always
    networks:
      - elastic
    depends_on:
      - es01

volumes:
  data02:
    driver: local

networks:
  elastic:
    driver: bridge
